- name: test class
  hosts: all
  become: yes
  tasks:
    - name: remove packages 
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - nginx
        - apache2

    - name: install package
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: create the file
      copy:
        content: "welcome jenkins ansible"
        dest: /var/www/html/

